# Generated by Django 5.2.11 on 2026-04-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggested_reward_minutes', models.PositiveIntegerField()),
                ('suggested_penalty_minutes', models.PositiveIntegerField(default=0)),
                ('suggested_time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('chore_type', models.CharField(choices=[('required', 'Required'), ('bonus', 'Bonus')], max_length=10)),
            ],
            options={
                'ordering': ['suggested_time_of_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chore_type', models.CharField(choices=[('required', 'Required'), ('bonus', 'Bonus')], max_length=10)),
                ('reward_minutes', models.PositiveIntegerField()),
                ('penalty_minutes', models.PositiveIntegerField(default=0)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('deadline_time', models.TimeField()),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom'), ('once', 'Once')], max_length=10)),
                ('recurrence_days', models.CharField(blank=True, default='', max_length=20)),
                ('recurrence_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('one_off_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(limit_choices_to={'role': 'kid'}, related_name='assigned_chores', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_of_day', 'deadline_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_instances', to=settings.AUTH_USER_MODEL)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.chore')),
            ],
            options={
                'ordering': ['due_date', 'chore__time_of_day', 'chore__deadline_time'],
                'unique_together': {('chore', 'assigned_to', 'due_date')},
            },
        ),
    ]
