# Generated by Django 5.2.11 on 2026-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_generate_chore_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='recurrence_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom'), ('once', 'Once')], max_length=10),
        ),
    ]
