# Generated by Django 5.2.11 on 2026-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timebanktransaction_timersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreinstance',
            name='penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
