# Generated by Django 5.2.11 on 2026-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_choreinstance_penalty_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timersession',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
