# Generated by Django 5.2.11 on 2026-04-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_timer_pause_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Can I have more time?', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
