# Generated by Django 5.2.11 on 2026-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_timerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animation_preference',
            field=models.CharField(choices=[('confetti', 'Confetti'), ('fireworks', 'Fireworks'), ('stars', 'Stars'), ('hearts', 'Hearts')], default='confetti', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sound_preference',
            field=models.CharField(choices=[('chime', 'Chime'), ('fanfare', 'Fanfare'), ('coin', 'Coin'), ('xylophone', 'Xylophone')], default='chime', max_length=20),
        ),
    ]
