# Generated by Django 5.2.11 on 2026-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_animation_preference_user_sound_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_color_1',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='bg_color_2',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='bg_use_gradient',
            field=models.BooleanField(default=False),
        ),
    ]
