# Generated by Django 5.2.11 on 2026-04-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_bg_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_pattern',
            field=models.CharField(choices=[('none', 'None'), ('stars', 'Stars'), ('polka', 'Polka Dots'), ('stripes', 'Stripes'), ('waves', 'Waves')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='font_style',
            field=models.CharField(choices=[('default', 'Default (Nunito)'), ('rounded', 'Rounded (Varela Round)'), ('handwritten', 'Handwritten (Patrick Hand)'), ('pixel', 'Pixel (Silkscreen)'), ('comic', 'Comic (Comic Neue)')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sidebar_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
