# Generated by Django 5.2.11 on 2026-04-09 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed(apps, schema_editor):
    from core.achievements import seed_achievements
    seed_achievements()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_visual_theme_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('emoji', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('streak', 'Streaks'), ('chore_count', 'Chore Count'), ('time_earned', 'Time Earned'), ('time_used', 'Time Used'), ('bonus', 'Bonus'), ('speed', 'Speed'), ('variety', 'Variety'), ('unlockable', 'Unlockable')], max_length=20)),
                ('criteria_type', models.CharField(max_length=30)),
                ('criteria_value', models.IntegerField()),
            ],
            options={
                'ordering': ['category', 'criteria_value'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='active_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_users', to='core.achievement'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_users', to='core.achievement'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='core.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
