# Generated by Django 5.2.11 on 2026-04-09 01:06

from django.db import migrations, models


def seed_new_achievements(apps, schema_editor):
    from core.achievements import seed_achievements
    seed_achievements()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_achievement_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='animation_preference',
            field=models.CharField(choices=[('confetti', 'Confetti'), ('fireworks', 'Fireworks'), ('stars', 'Stars'), ('hearts', 'Hearts'), ('bubbles', 'Bubbles'), ('rainbow', 'Rainbow'), ('sparkle', 'Sparkle'), ('snow', 'Snow')], default='confetti', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg_pattern',
            field=models.CharField(choices=[('none', 'None'), ('stars', 'Stars'), ('polka', 'Polka Dots'), ('stripes', 'Stripes'), ('waves', 'Waves'), ('checkerboard', 'Checkerboard'), ('zigzag', 'Zigzag'), ('diamonds', 'Diamonds')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sound_preference',
            field=models.CharField(choices=[('chime', 'Chime'), ('fanfare', 'Fanfare'), ('coin', 'Coin'), ('xylophone', 'Xylophone'), ('laser', 'Laser'), ('powerup', 'Power Up'), ('levelup', 'Level Up'), ('applause', 'Applause'), ('drumroll', 'Drumroll')], default='chime', max_length=20),
        ),
        migrations.RunPython(seed_new_achievements, migrations.RunPython.noop),
    ]
