# Generated by Django 5.2.11 on 2026-05-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_multi_completions_and_optional_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='timer_prerequisite',
            field=models.BooleanField(default=False),
        ),
    ]
