# Generated by Django 5.2.11 on 2026-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chore_timer_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
    ]
