"""Core models for ChoreBank.

Custom User model with role (parent/kid) and emoji avatar.
Chore system: Chore (definition), ChoreInstance (per-kid occurrence),
ChoreTemplate (pre-built suggestions for parents).
Time bank: TimeBankTransaction (append-only ledger), TimerSession (timer usage).
"""

from collections import defaultdict
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Sum
from django.utils.timezone import localdate


class User(AbstractUser):
    """Custom user with role and avatar for ChoreBank family members."""

    class Role(models.TextChoices):
        PARENT = "parent", "Parent"
        KID = "kid", "Kid"

    role = models.CharField(max_length=10, choices=Role.choices)
    emoji_avatar = models.CharField(max_length=10, default="\U0001f600")

    @property
    def is_parent(self):
        """Return True if user has parent role."""
        return self.role == self.Role.PARENT

    @property
    def is_kid(self):
        """Return True if user has kid role."""
        return self.role == self.Role.KID

    class Meta:
        db_table = "core_user"

    def __str__(self):
        return f"{self.emoji_avatar} {self.first_name}"


class Chore(models.Model):
    """Chore definition created by parents. Recurrence rules determine
    when ChoreInstance records are generated."""

    class ChoreType(models.TextChoices):
        REQUIRED = "required", "Required"
        BONUS = "bonus", "Bonus"

    class TimeOfDay(models.TextChoices):
        MORNING = "morning", "Morning"
        AFTERNOON = "afternoon", "Afternoon"
        EVENING = "evening", "Evening"

    class RecurrenceType(models.TextChoices):
        DAILY = "daily", "Daily"
        WEEKLY = "weekly", "Weekly"
        MONTHLY = "monthly", "Monthly"
        CUSTOM = "custom", "Custom"
        ONCE = "once", "Once"

    name = models.CharField(max_length=100)
    chore_type = models.CharField(max_length=10, choices=ChoreType.choices)
    reward_minutes = models.PositiveIntegerField()
    penalty_minutes = models.PositiveIntegerField(default=0)
    time_of_day = models.CharField(max_length=10, choices=TimeOfDay.choices)
    deadline_time = models.TimeField()
    assigned_to = models.ManyToManyField(
        "User",
        related_name="assigned_chores",
        limit_choices_to={"role": "kid"},
    )
    recurrence_type = models.CharField(
        max_length=10, choices=RecurrenceType.choices
    )
    recurrence_days = models.CharField(max_length=20, blank=True, default="")
    recurrence_interval = models.PositiveIntegerField(null=True, blank=True)
    one_off_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(
        "User", on_delete=models.CASCADE, related_name="created_chores"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["time_of_day", "deadline_time", "name"]

    def __str__(self):
        return self.name


class ChoreInstance(models.Model):
    """Per-kid-per-date occurrence of a chore. Generated by the nightly
    task and marked complete by kids or parents."""

    chore = models.ForeignKey(
        Chore, on_delete=models.CASCADE, related_name="instances"
    )
    assigned_to = models.ForeignKey(
        "User", on_delete=models.CASCADE, related_name="chore_instances"
    )
    due_date = models.DateField()
    completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)
    penalty_applied = models.BooleanField(default=False)

    class Meta:
        unique_together = ["chore", "assigned_to", "due_date"]
        ordering = [
            "due_date",
            "chore__time_of_day",
            "chore__deadline_time",
        ]

    def __str__(self):
        return f"{self.chore.name} - {self.assigned_to} ({self.due_date})"

    @classmethod
    def _streak_data(cls, kid):
        """Return per-date completion data for the last 30 days.

        Returns a dict mapping date -> (total_required, completed_required).
        Only considers required chores (bonus chores don't break streaks).
        Days with zero required chores are skipped.
        """
        today = localdate()
        start = today - timedelta(days=30)
        instances = cls.objects.filter(
            assigned_to=kid,
            due_date__gte=start,
            due_date__lte=today,
            chore__chore_type="required",
        ).values_list("due_date", "completed")

        by_date = defaultdict(lambda: [0, 0])  # [total, completed]
        for due_date, completed in instances:
            by_date[due_date][0] += 1
            if completed:
                by_date[due_date][1] += 1
        return today, by_date

    @classmethod
    def get_streak(cls, kid):
        """Compute the current consecutive-day streak for a kid.

        A day counts as completed if ALL required chores for that day are done.
        Days with no required chores are skipped (don't break streak).
        Starts counting from today (or yesterday if today has incomplete chores).
        """
        today, by_date = cls._streak_data(kid)
        streak = 0
        for i in range(31):
            d = today - timedelta(days=i)
            if d not in by_date:
                continue  # no required chores this day, skip
            total, done = by_date[d]
            if done >= total:
                streak += 1
            else:
                # Today incomplete is okay -- might not be done yet
                if i == 0:
                    continue
                break
        return streak

    @classmethod
    def get_longest_streak(cls, kid):
        """Compute the longest consecutive-day streak in the last 30 days."""
        today, by_date = cls._streak_data(kid)
        longest = 0
        current = 0
        for i in range(30, -1, -1):
            d = today - timedelta(days=i)
            if d not in by_date:
                continue  # skip days with no required chores
            total, done = by_date[d]
            if done >= total:
                current += 1
                longest = max(longest, current)
            else:
                current = 0
        return longest


class ChoreTemplate(models.Model):
    """Pre-built chore suggestions for parents to quickly create chores."""

    name = models.CharField(max_length=100)
    suggested_reward_minutes = models.PositiveIntegerField()
    suggested_penalty_minutes = models.PositiveIntegerField(default=0)
    suggested_time_of_day = models.CharField(
        max_length=10, choices=Chore.TimeOfDay.choices
    )
    chore_type = models.CharField(
        max_length=10, choices=Chore.ChoreType.choices
    )

    class Meta:
        ordering = ["suggested_time_of_day", "name"]

    def __str__(self):
        return self.name


class TimeRequest(models.Model):
    """Kid requests more screen time from parents."""

    kid = models.ForeignKey(
        "User", on_delete=models.CASCADE, related_name="time_requests"
    )
    message = models.CharField(max_length=100, default="Can I have more time?")
    created_at = models.DateTimeField(auto_now_add=True)
    dismissed = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.kid.first_name}: {self.message}"


class TimeBankTransaction(models.Model):
    """Append-only ledger entry for time bank balance changes."""

    class TransactionType(models.TextChoices):
        EARN = "earn", "Earn"
        SPEND = "spend", "Spend"
        PENALTY = "penalty", "Penalty"
        ADJUST = "adjust", "Adjust"

    kid = models.ForeignKey(
        "User", on_delete=models.CASCADE, related_name="bank_transactions"
    )
    transaction_type = models.CharField(
        max_length=10, choices=TransactionType.choices
    )
    amount = models.IntegerField(
        help_text="Minutes: positive adds time, negative subtracts"
    )
    note = models.CharField(max_length=200, blank=True, default="")
    created_by = models.ForeignKey(
        "User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="created_transactions",
    )
    chore_instance = models.ForeignKey(
        ChoreInstance,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["kid", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.get_transaction_type_display()} {self.amount}m for {self.kid}"

    @classmethod
    def get_balance(cls, kid):
        """Return total balance in minutes for a kid (sum of all transactions)."""
        result = cls.objects.filter(kid=kid).aggregate(total=Sum("amount"))
        return result["total"] or 0


def format_balance(minutes):
    """Format a balance in minutes as a human-readable string (e.g. 2h 15m)."""
    if minutes == 0:
        return "0m"
    sign = "-" if minutes < 0 else ""
    abs_min = abs(minutes)
    if abs_min >= 60:
        h, m = divmod(abs_min, 60)
        return f"{sign}{h}h {m}m" if m else f"{sign}{h}h"
    return f"{sign}{abs_min}m"


class TimerSession(models.Model):
    """Records timer usage — links to a SPEND transaction at start."""

    kid = models.ForeignKey(
        "User", on_delete=models.CASCADE, related_name="timer_sessions"
    )
    requested_minutes = models.PositiveIntegerField()
    started_at = models.DateTimeField()
    ended_at = models.DateTimeField(null=True, blank=True)
    ended_reason = models.CharField(max_length=20, default="manual")
    spend_transaction = models.OneToOneField(
        TimeBankTransaction,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="timer_session_spend",
    )
    paused_at = models.DateTimeField(null=True, blank=True)
    paused_seconds = models.PositiveIntegerField(default=0)

    @property
    def actual_minutes(self):
        """Return elapsed minutes if session has ended, else 0."""
        if self.ended_at:
            elapsed = (self.ended_at - self.started_at).total_seconds()
            return int((elapsed - self.paused_seconds) / 60)
        return 0

    class Meta:
        ordering = ["-started_at"]

    def __str__(self):
        return f"{self.kid} - {self.requested_minutes}m ({self.ended_reason})"
